# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day at 6am)
  schedule: [{cron: "0 6 * * 3"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}

          # Options
          user: MerajCode
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          base_skip: yes
          commits_authoring: merajcode
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Calcutta
          config_twemoji: yes
          plugin_calendar: yes
          plugin_calendar_limit: 1
          # plugin_achievements: yes
          # plugin_achievements_display: compact
          # plugin_achievements_limit: 10
          # plugin_achievements_secrets: yes
          # plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++,c#, python, ejs
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 5
          plugin_leetcode_sections: solved
          plugin_leetcode_user: merajcode
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          repositories_batch: 100
          repositories_forks: yes
          extras_css: |
            h2:not(:first-child) { display: none !important; }
